#!/bin/bash
set -eu

key=$1
mapfile -t

if [[ $1 == 1 ]]; then
  exiftran -1i "${MAPFILE[@]}"
elif [[ $1 == 2 ]]; then
  exiftran -2i "${MAPFILE[@]}"
elif [[ $1 == 9 ]]; then
  exiftran -9i "${MAPFILE[@]}"
elif [[ $key == d ]]; then
  for path in "${MAPFILE[@]}"; do
    directory=${path%/*}
    filename=${path##*/}
    mv "$path" "$directory"/."$filename"
  done
elif [[ $key == e ]]; then
  gimp "${MAPFILE[@]}"
elif [[ $key == y ]]; then
  printf '%s\n' "${MAPFILE[@]}" | head -c -1 | xsel -b
fi
