#!/bin/bash
set -eu

if [[ $1 == d ]]; then
  xargs -d '\n' bash -"$-" -c 'for path; do mv "$path" "${path%/*}"/."${path##*/}"; done' --
elif [[ $1 == e ]]; then
  xargs -d '\n' gimp
elif [[ $1 == y ]]; then
  head -c -1 | xsel -b
elif [[ $1 == m ]]; then
  mapfile -t
  path=$XDG_RUNTIME_DIR/sxiv-target
  x-terminal-emulator -e vifm --choose-dir="$path" "${MAPFILE[0]%/*/*}"
  mv "${MAPFILE[@]}" "$(< "$path")"
fi
