[colors.bright]
black = "#000000"

[colors.normal]
black = "#ffffff"
blue = "#000000"
cyan = "#000000"
green = "#000000"
magenta = "#000000"
red = "#000000"
white = "#000000"
yellow = "#000000"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[cursor]
unfocused_hollow = false

[font]
size = 14

[font.normal]
family = "DejaVu Sans Mono"

[font.offset]
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "exec tmux new-session -A -s 0"]
program = "/bin/bash"

[window]
decorations = "None"
title = "Terminal"

[window.dimensions]
columns = 124
lines = 32
