- become: yes
  block:
    - apt:
        cache_valid_time: 1000000
        name: aptitude
    - register: aptitude
      stat:
        path: /var/log/aptitude
    - apt:
        upgrade: yes
      when: not aptitude.stat.exists
- block:
    - register: reboot
      stat:
        path: /run/reboot-required
    - block:
        - pause:
            prompt: 'Reboot? [Y/n]'
          register: prompt
        - become: yes
          command: reboot
          when: not prompt.user_input or prompt.user_input[0].lower() == 'y'
      when: reboot.stat.exists
