- connection: local
  hosts: localhost
  tasks:
    - become: yes
      user:
        name: danil
        groups: adm,audio,cdrom,dialout,games,gpio,i2c,input,netdev,plugdev,spi,sudo,users,video
      when: ansible_hostname == 'raspberrypi'
    - become: yes
      shell: 'gpasswd -d pi sudo || :'
      when: ansible_hostname == 'raspberrypi'
    - apt:
        cache_valid_time: 1000000
        name: unattended-upgrades
      become: yes
    - register: aptitude
      stat:
        path: /var/log/aptitude
    - apt:
        cache_valid_time: 1000000
        upgrade: yes
      become: yes
      when: not aptitude.stat.exists
