- connection: local
  hosts: localhost
  tasks:
    - command: grep -Po '(?<=^ID=).+' /etc/os-release
      register: raspbian
    - include: includes/raspbian.yml
      when: raspbian.stdout == 'raspbian'
    - include: includes/dotfiles.yml
    - become: yes
      copy:
        content: |
          [Service]
          ExecStart=
          ExecStart=-/usr/bin/agetty -a $USER %I
          Type=simple
        dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    - apt:
        cache_valid_time: 1000000
        name: unattended-upgrades
      become: yes
    - include: includes/upgrade.yml
