- connection: local
  hosts: localhost
  tasks:
    - include: includes/raspbian.yml
      when: ansible_hostname == 'raspberrypi'
    - apt:
        cache_valid_time: 1000000
        name: unattended-upgrades
      become: yes
    - include: includes/upgrade.yml
