- connection: local
  hosts: localhost
  tasks:
    - block:
        - command: grep -Po '(?<=^ID=).+' /etc/os-release
          register: release
        - include: 'includes/{{item}}.yml'
          when: release.stdout == item
          with_list:
            - debian
            - raspberry
    - include: includes/dotfiles.yml
    - become: yes
      block:
        - replace:
            dest: /etc/default/keyboard
            regexp: '(?<=^XKBLAYOUT=")[^"]*'
            replace: 'us,ru'
        - block:
            - file:
                path: '{{path}}'
                recurse: yes
                state: directory
            - copy:
                content: |
                  [Service]
                  ExecStart=
                  ExecStart=-/sbin/agetty -a {{ansible_user}} %I
                dest: '{{path}}/autologin.conf'
          vars:
            path: /etc/systemd/system/getty@tty1.service.d
        - block:
            - file:
                dest: '/etc/systemd/system/{{name}}.service'
                src: '{{path}}/{{name}}.service'
                state: link
            - command: 'systemctl enable {{path}}/{{name}}.timer'
          vars:
            name: fstrim
            path: /usr/share/doc/util-linux/examples
        - copy:
            content: '%sudo ALL = (ALL) NOPASSWD: /usr/bin/apt -y install'
            dest: /etc/sudoers.d/apt-install
        - copy:
            content: '%sudo ALL = (ALL) NOPASSWD: SETENV: /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall'
            dest: /etc/sudoers.d/sshuttle
        - apt:
            cache_valid_time: 1000000
            name: unattended-upgrades
    - include: includes/upgrade.yml
