- connection: local
  hosts: localhost
  tasks:
    - command: grep -Po '(?<=^ID=).+' /etc/os-release
      register: raspbian
    - include: includes/raspbian.yml
      when: raspbian.stdout == 'raspbian'
    - include: includes/dotfiles.yml
    - apt:
        cache_valid_time: 1000000
        name: unattended-upgrades
      become: yes
    - include: includes/upgrade.yml
