- connection: local
  hosts: localhost
  tasks:
    - block:
        - command: grep -Po '(?<=^ID=).+' /etc/os-release
          register: release
        - include: 'includes/{{item}}.yml'
          when: release.stdout == item
          with_list:
            - debian
            - raspberry
    - include: includes/dotfiles.yml
    - become: yes
      block:
        - replace:
            dest: /etc/default/keyboard
            regexp: '(?<=^XKBLAYOUT=")[^"]*'
            replace: 'us,ru'
        - block:
            - file:
                path: '{{path}}'
                recurse: yes
                state: directory
            - copy:
                content: |
                  [Service]
                  ExecStart=
                  ExecStart=-/sbin/agetty -a {{ansible_user}} %I
                dest: '{{path}}/autologin.conf'
                force: no
          vars:
            path: /etc/systemd/system/getty@tty1.service.d
        - apt:
            cache_valid_time: 1000000
            name: unattended-upgrades
    - include: includes/upgrade.yml
